/**
 * OpenHypothesis lifecycle hooks for OpenCode.
 *
 * Auto-generated by `openhypothesis-opencode init`.
 * This plugin provides:
 *   - Session context injection (onSessionCreated / config hook)
 *   - Tool execution logging to DuckDB (onToolExecute / before hook)
 *   - Lab inventory re-indexing on file edit (onFileEdited / after hook)
 */

/// <reference types="@opencode-ai/plugin" />

/**
 * @param {import("@opencode-ai/plugin").PluginInput} input
 * @returns {Promise<import("@opencode-ai/plugin").Hooks>}
 */
export default async function ({ client, project, directory, $ }) {
  return {

    /**
     * onSessionCreated — inject AGENTS.md into the instructions list
     * so the agent loads the project conventions automatically.
     */
    config: (cfg) => {
      const instructions = cfg.instructions || [];
      if (!instructions.includes("AGENTS.md")) {
        instructions.push("AGENTS.md");
      }
      cfg.instructions = instructions;
    },

    /**
     * onToolExecute — log bash commands to the DuckDB audit store.
     * Only logs commands that match search-related patterns.
     */
    "tool.execute.before": async (input, output) => {
      if (input.tool === "bash" && input.args?.command?.includes("search")) {
        const dbPath = process.env.OPENHYPOTHESIS_DB || "./duckdb_data/audit.duckdb";
        const safeCommand = JSON.stringify(input.args.command).replace(/'/g, "''");
        $(`duckdb ${dbPath} "INSERT INTO tool_log VALUES ('${input.tool}', '${safeCommand}', CURRENT_TIMESTAMP)"`).catch(() => {
          // Silently ignore — DuckDB may not be available
        });
      }
    },

    /**
     * onFileEdited — detect lab inventory CSV edits and trigger re-index.
     */
    "tool.execute.after": async (input, output) => {
      if (input.tool === "edit" && input.filePath?.endsWith("inventory.csv")) {
        console.log("Lab inventory changed — re-indexing...");
        $("uv run python -m openhypothesis.tools.ingest --inventory").catch(() => {
          console.log("Re-index failed. Check that openhypothesis is installed.");
        });
      }
    },

  };
};
